### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ilyar** [EverscaleGuild/TestSuite#1]
# Roadmap

- [x] Marge PRs  from https://github.com/tonlabs/TestSuite4/pulls
  - [x] https://github.com/tonlabs/TestSuite4/pull/15
  - [x] https://github.com/tonlabs/TestSuite4/pull/16
- [x] Update readme
- [ ] Update package
- [ ] Add tests on CI
- [ ] Update `linker_lib`
- [ ] Maybe switch thema docs into https://github.com/peaceiris/mkdocs-material-boilerplate
- [ ] TBD...
